from . import back_button
from . import language_menu
from . import main_menu
from . import settings_menu
from . import contacts
from . import locations
from . import cart_overall_ready
from . import select_deliver_type_menu
from . import confirmation_menu
from . import deliver_options_menu
from . import deliver_time_menu
from . import orders_hitory_menu
from . import payment_method_menu
